Section "Device"
    Identifier "Intel"
    Driver "intel"
    BusID "PCI:0:2:0"
EndSection

Section "Monitor"
    Identifier "DP-1-0"
    Option "Primary" "true"
EndSection

Section "Monitor"
    Identifier "eDP-1"
    Option "Ignore" "true"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Intel"
    Monitor "DP-1-0"
EndSection
